# taplo：TOML 格式化与校验
include = ["**/*.toml"]
exclude = ["Cargo.lock", "target/**", ".devenv/**", ".direnv/**"]

[formatting]
align_entries = false
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = true
compact_inline_tables = false
indent_tables = false
indent_entries = false
indent_string = "  "
trailing_newline = true
reorder_keys = false
allowed_blank_lines = 1
