[package]
name = "nomic-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
nomic-ai.workspace = true
nomic-core.workspace = true
nomic-skills.workspace = true
globset.workspace = true
grep-regex.workspace = true
grep-searcher.workspace = true
ignore.workspace = true
nix.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
